In [1]:
from src.embedder import TextEmbedder

/Users/tibortamas/anaconda3/envs/moverscore_development/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
embedder = TextEmbedder()

In [3]:
test = ['The big blue whale in the ocean', 'The ocean blue car passed the corner', 'Harry Potter and the half blood prince']

In [4]:
embedder.create_idf_dict(test)

defaultdict(<function src.embedder.TextEmbedder.create_idf_dict.<locals>.<lambda>()>,
            {13156: 0.6931471805599453,
             101: 0.0,
             2502: 0.6931471805599453,
             102: 0.0,
             2630: 0.28768207245178085,
             1996: 0.0,
             1999: 0.6931471805599453,
             4153: 0.28768207245178085,
             2979: 0.6931471805599453,
             2482: 0.6931471805599453,
             3420: 0.6931471805599453,
             10693: 0.6931471805599453,
             2668: 0.6931471805599453,
             1998: 0.6931471805599453,
             4302: 0.6931471805599453,
             3159: 0.6931471805599453,
             2431: 0.6931471805599453})

In [5]:
total_embedding, seq_lengths, attention_mask, padded_idf, tokens = embedder(test, batch_size=1)

In [6]:
seq_lengths

tensor([8, 8, 9])

In [7]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
padded_idf

tensor([[0.6931, 0.0000, 0.2877, 0.6931, 0.0000, 0.0000, 0.6931, 0.2877, 0.0000],
        [0.6931, 0.0000, 0.2877, 0.0000, 0.0000, 0.6931, 0.2877, 0.6931, 0.0000],
        [0.6931, 0.0000, 0.0000, 0.0000, 0.6931, 0.6931, 0.6931, 0.6931, 0.6931]])

In [9]:
tokens

[['[CLS]', 'the', 'big', 'blue', 'whale', 'in', 'the', 'ocean', '[SEP]'],
 ['[CLS]', 'the', 'ocean', 'blue', 'car', 'passed', 'the', 'corner', '[SEP]'],
 ['[CLS]',
  'harry',
  'potter',
  'and',
  'the',
  'half',
  'blood',
  'prince',
  '[SEP]']]

In [10]:
total_embedding.size()

torch.Size([3, 9, 768])

In [11]:
total_embedding[0]

tensor([[-0.1707, -0.0730,  0.0850,  ..., -0.0722,  0.0944,  0.1601],
        [-0.1616, -0.1101,  0.0556,  ..., -0.0934,  0.1780,  0.1683],
        [-0.2074, -0.4122,  0.3279,  ..., -0.0498,  0.0423, -0.1078],
        ...,
        [-0.2591, -0.2822, -0.0546,  ...,  0.0587,  0.0332,  0.1317],
        [-0.0274, -0.2099,  0.3109,  ..., -0.1119,  0.3133,  0.1132],
        [-0.0556, -0.2880,  0.1174,  ...,  0.2807,  0.0242,  0.2298]])